### ISSUE TITLE
annotations dependant on Python 3.7

### ISSUE THREAD

**Issue by gezpage** [dkraczkowski/opyapi#12]
Package has a dependency on Python 3.6  yet `annotations` is not available until Python 3.7

https://github.com/dkraczkowski/opyapi/blob/master/pyproject.toml#L24
https://www.python.org/dev/peps/pep-0563/

```
Traceback (most recent call last):
  File "pyapi/api.py", line 1, in <module>
    from opyapi.api import *
  File "/Users/skinnycode/Dev/personal/pyapi/.venv/src/opyapi/opyapi/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/skinnycode/Dev/personal/pyapi/.venv/src/opyapi/opyapi/application.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by dkraczkowski** [comment]
Guess I will need to remove annotations from the source code.
